# reference: https://www.appveyor.com/docs/appveyor-yml/

version: 0.3.{build}

# build all branches by default

image: Visual Studio 2017
platform: x64
configuration: Release

clone_folder: c:\projects\onnx
clone_depth: 2

# pick as per https://www.appveyor.com/docs/build-environment/#python
environment:
  matrix:
  - ONNX_ML: 1
    PYTHON: "C:\\Python37-x64"
    PYTHON_VERSION: "3.7.x"
    PYTHON_ARCH: "64"
    
install:
- cmd: git submodule update --init --recursive

before_build:
- "%PYTHON%\\Scripts\\pip install pymyinstall"
- "%PYTHON%\\Scripts\\pymy_install protobuf numpy --source=2"
- "%PYTHON%\\Scripts\\pip install wheel"
- "%PYTHON%\\Scripts\\pip install typing six typing-extensions pytest nbval pytest-cov tabulate pytest-runner"

build_script:
# Build and test protobuf
- cd ..
- mkdir protobuf
- git clone --recursive https://github.com/protocolbuffers/protobuf.git
- set vcplatform=x64
- set platform=Win64
- set configuration=Release
- set generator=Visual Studio 15 Win64
- set language=cpp
- cd protobuf
- cmd: appveyor
- cd ..
- cd onnx

# Build and test onnx.
- cd c:\projects\onnx
- copy c:\projects\onnx\third_party\pybind11\tools\pybind11Config.cmake.in c:\projects\onnx\third_party\pybind11\tools\pybind11Config.cmake
- set CMAKE_ARGS=-Dpybind11_DIR=c:\\projects\\onnx\\third_party\\pybind11\\tools -DPROTOBUF_INCLUDE_DIRS=c:\\projects\\protobuf\\src -DPROTOBUF_LIBRARIES=c:\\projects\\protobuf\\build_msvc\\Release\\libprotobuf.lib;c:\\projects\\protobuf\\build_msvc\\Release\\libprotoc.lib -DONNX_PROTOC_EXECUTABLE=c:\\projects\\protobuf\\build_msvc\\Release\\protoc.exe
- "%PYTHON%\\python setup.py bdist_wheel --universal"
- set language=cpp
- "%PYTHON%\\python onnx\\defs\\gen_doc.py"
- "%PYTHON%\\python onnx\\gen_proto.py"
- set language=py
- "%PYTHON%\\python onnx\\defs\\gen_doc.py"
- "%PYTHON%\\python onnx\\gen_proto.py"

artifacts:
  - path: dist
    name: onnx
    
  - path: protobuf\build_msvc\Release    
    name: protobuf
  